site_name: Aether Help
nav:
- Home: index.md
- Getting Started:
  - Installing Aether: installing.md
  - Getting Started: gettingstarted.md
  - Preferences: preferences/preferences.md
  - Station Info: stationinfo.md
  - Callbook Lookup: callbooklookup/callbooklookup.md
  - Rig Control: rigcontrol/rigcontrol.md
  - Awards Tracking: awards/awardstracking.md
- Guides:
  - Awards Tracking:
    - Basics: awards/awardstracking.md
    - Custom Awards: awards/customawards.md
  - Callbook Lookup:
    - Basics: callbooklookup/callbooklookup.md
    - Troubleshooting: callbooklookup/callbooktroubleshooting.md
  - Contest Logging:
    - Cabrillo: contesting/cabrillo.md
    - TX/RX Exch.: contesting/txrxexch.md
  - Import/Export: importexport.md
  - eQSL.cc:
    - Basics: eqsl/eqsl.md
    - Troubleshooting: eqsl/eqsltroubleshooting.md
  - Logbook of the World:
    - Setup: lotw/lotwsetup.md
    - Certificates:
      - Requesting a Certificate: lotw/requestcertificate.md
      - Installing a Certificate: lotw/installcertificate.md
      - Exporting p12 Files: lotw/exportp12.md
      - Troubleshooting Certificates: lotw/certificatetroubleshooting.md
    - LoTW Settings: preferences/qslpreferences.md
    - Syncing with LoTW: lotw/syncinglotw.md
    - Troubleshooting:
      - Overview: lotw/lotwtroubleshootingoverview.md
      - Certificates: lotw/certificatetroubleshooting.md
      - Uploads to LoTW: lotw/lotwuploadtroubleshooting.md
  - Preferences:
    - Overview: preferences/preferences.md
    - General: preferences/generalpreferences.md
    - Rig Control: preferences/rigcontrolpreferences.md
    - Logging: preferences/loggingpreferences.md
    - QSL: preferences/qslpreferences.md
    - Awards Tracking: preferences/awardspreferences.md
    - Hidden Preferences: preferences/hiddenpreferences.md
  - Printing:
    - Logbooks: printing/logbooks.md
    - Labels: printing/labels.md
  - Rig Control:
    - Overview: rigcontrol/rigcontrol.md
    - Interfaces: rigcontrol/riginterfaces.md
    - Drivers: rigcontrol/rigdrivers.md
    - Supported Radios: rigcontrol/supportedrigs.md
    - Settings: preferences/rigcontrolpreferences.md
    - PTT (Expert): rigcontrol/ptt.md
    - Troubleshooting: rigcontrol/troubleshooting.md
  - Miscellaneous:
    - Debug Log: misc/debuglog.md
    - Country Files: misc/countryfiles.md
    - Google Earth Integration: misc/googleearth.md
    - Logging Using aether:// URLs: misc/logurl.md
- FAQ:
  - Lost Logbook: faq/lostlog.md
  - Lost License: faq/lostlicense.md
  - Aether Betas: faq/beta.md
  - Mode Support: faq/modedropdown.md
  - Old Versions: faq/oldversions.md

theme: flatly

markdown_extensions:
  - attr_list
